spring:
  profiles:
    active: dev

  application:
    name: "sistema_reservas"

  output:
    ansi:
      enabled: always

  sql:
    init:
      encoding: UTF-8

application:
  security:
    jwt:
      expiration: 130
      refresh-expiration: 300
