spring:
  profiles:
    active: dev

  application:
    name: "sistema_reservas"

  jpa:
    open-in-view: false
    properties:
      hibernate:
        ddl-auto: update

  output:
    ansi:
      enabled: always

  sql:
    init:
      encoding: UTF-8

application:
  security:
    jwt:
      expiration: 130
      refresh-expiration: 300
